### ISSUE TITLE
Wrong report for sparse checkouts

### ISSUE THREAD

**Issue by ntadej** [romkatv/gitstatus#107]
I'm using sparse checkout on a large repository and I get the following report (using powerlevel10k):
```
*7 !64522 ?20
```
I see no unstaged or untracked files with git status.

- The unstaged number seems to be related to files that are not checked-out.
- The untracked number seems to be related to ignored files (which seem not to be ignored here).

**Comment by romkatv** [comment]
gitstatusd uses libgit2 to make the final assessment on the dirty candidates, and libgit2 doesn't support sparse checkout. I'm using a fork of libgit2 where I've implemented many performance improvements but I'm not up to the task of implementing sparse checkout. Sorry. Once libgit2 implements sparse checkout, gitstatusd will handle your case. Here's the issue you might want to follow: https://github.com/libgit2/libgit2/issues/2263.

**Comment by ntadej** [comment]
Thanks for the clarification and sorry for the noise.

**Comment by Mellbourn** [comment]
I took a look at that issue in libgit2, and unfortunately, it is *seven years* old. So, it seems it might not get fixed shortly. 

Is there any way to do a workaround? To me, it would be an improvement to detect if we're in a sparse checkout and just not show the unstaged file count at all since it is meaningless and distracting right now.

**Comment by romkatv** [comment]
> To me, it would be an improvement to detect if we're in a sparse checkout and just not show the unstaged file count at all, since right now it is meaningless and distracting.

You can do this by modifying `my_git_formatter` in your `~/.p10k.zsh`.

Alternatively, run this in your sparse repo:

```zsh
git config --local bash.showUntrackedFiles false
git config --local bash.showDirtyState false
```

These settings only affect prompt. They'll disable the computation and the display of untracked files and staged, unstaged and conflicted changes. You'll also get an indicator in your prompt hinting that some stats are missing (`─`).

The names of these config options start with "bash" because they were introduced in https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh. I've made gitstatusd respect the same options.
