### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Ambyjkl** [romkatv/gitstatus#213]
gitstatus has memory usage anywhere from 150 to 300 MB for large git repos, such as chromium source code. And the problem multiplies with the number of zsh sessions I have with powerlevel10k running.

**Comment by romkatv** [comment]
> gitstatus has memory usage anywhere from 150 to 300 MB for large git repos, such as chromium source code.

That's in the ballpark I would expect for the current implementation. If you want to reduce it, please send a PR.

**Comment by Ambyjkl** [comment]
In that case, how about freeing the memory a certain amount of time after cding out of the repo, since it only takes one cd into the folder, and that memory is stuck until I close the shell.

**Comment by romkatv** [comment]
> In that case, how about freeing the memory a certain amount of time after cding out of the repo

That's how it works. You can specify the amount of time with `--repo-ttl-seconds`. The default is 3600 (one hour). Granted, freeing memory doesn't necessarily mean it'll be released to the OS. This is up to the allocator.

Anyway, if this is important to you, send a PR. I won't be working on this.

**Comment by Ambyjkl** [comment]
Ok cool, I'll try configuring `--repo-ttl-seconds`. As for how this problem can be mitigated:
- Reduce memory used directly
- Shared instance for all shell sessions

I won't have the time to implement stuff right now, but maybe in the future.

**Comment by denilsonsa** [comment]
@romkatv Hello! Do you have any pointers on how to pass this TTL parameter? Where can we set this configuration? What should I set on my `~/.zshrc`?

I have noticed the [sh plugin](https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.sh#L39-L42) has a `-r` parameter that gets the default value of 3600; but I see nothing on the [zsh plugin](https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.zsh). But maybe I'm not looking at the right place.

For context, I'm using [powerlevel10k zsh theme](https://github.com/romkatv/powerlevel10k), which by the way comes preinstalled and preconfigured on Manjaro. And I'm finding this issue here because I have one gitstatusd instance taking 867MB of RAM, plus five other instances taking over 200MB each (which means about 2GB of RAM just for gitstatusd). I need to find a way to tame down the beast ;) .

**Comment by romkatv** [comment]
> @romkatv Hello! Do you have any pointers on how to pass this TTL parameter?

Why do you want to pass it? Do you want to increase or decrease it and why?

> I need to find a way to tame down the beast ;)

gitstatusd needs memory to do its job. If you sometimes find yourself going into a massive repo and then leaving and never coming back, this repo will stay in memory for one hour. You can run `exec zsh` to manually evict it.
