### ISSUE TITLE
make it simple to use from dumb scripts

### ISSUE THREAD

**Issue by grosser** [romkatv/gitstatus#25]
I'd love for `gitstatusd` to return some useful output for the current directory, so that simple prompt scripts can call it and then say "did output include X" -> show "up to date".
Alternatively make `echo "." | gitstatusd` work.

For example I'm using a very low-tech prompt and would like to use gitstatusd but was unable to get it working.

https://github.com/grosser/dotfiles/blob/master/bash/prompt.sh#L13-L38

**Comment by romkatv** [comment]
`gitstatusd` is easy to use from scripts (at least easier than using `git status`) provided that they are written in ZSH. It would be nice to have similar API for bash but it doesn't exist at the moment.

I translated a subset of the functionality from ZSH API to bash and added an example of how it can be used to set `PS1`. It's in [bash-prompt-example.sh](https://github.com/romkatv/gitstatus/blob/master/bash-prompt-example.sh). This code is already usable despite missing many features. I've also opened https://github.com/romkatv/gitstatus/issues/26. I don't intend to work on it but I'll be happy to receive PRs.

Is this satisfactory?

**Comment by grosser** [comment]
thx, this is a great starting point :)

I was hoping I could shell out to gitstatus and get a reply without managing a daemon
(simple/safe but small overhead)

**Comment by romkatv** [comment]
> I was hoping I could shell out to gitstatus and get a reply

Sure, you can do that. Hopefully it's clear how from the example.

> without managing a daemon

Note that the example already contains code for managing the daemon. More specifically, the daemon starts and stops together with an interactive bash session. There is one corner case though. If you start bash and then type `exec cat` and leave it be, you'll have a useless `gitstatusd` process doing nothing until `cat` exits. While I wouldn't release official bash bindings without this corner case being addressed, this is unlikely to cause problems in practice because it's rather unusual to `exec` from an interactive shell. Plus, a useless `gitstatusd` isn't expensive.

> small overhead

The difference in performance is about an order of magnitude. It's immediately apparent if you work on anything other than tiny git repos.

**Comment by romkatv** [comment]
FYI: gitstatus now has official bash bindings: https://github.com/romkatv/gitstatus/#using-from-bash.

**Comment by grosser** [comment]
awesome, thx!
