### ISSUE TITLE
Avoid resetting the `PROMPT_COMMAND` for bash

### ISSUE THREAD

**Issue by dhruvmanila** [romkatv/gitstatus#263]
It is recommended to include the previous value when setting the `PROMPT_COMMAND` value:

Source: `/etc/bashrc_Apple_Terminal:80`
```bash
# If you customize PROMPT_COMMAND be sure to include the previous value. e.g.,
#
#   PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }your_code_here"
```

https://github.com/romkatv/gitstatus/blob/master/gitstatus.prompt.sh#L88

**Comment by romkatv** [comment]
Where is it recommended? If you mean the quote from Apple, it's hard to trust it given that it's buggy. Try it:

```bash
bash-5.0$ PROMPT_COMMAND='echo hello;'
hello
bash-5.0$ PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }echo bye"
bash: PROMPT_COMMAND: line 2: syntax error near unexpected token `;;'
bash: PROMPT_COMMAND: line 2: `echo hello;; echo bye'
bash-5.0$
```

As you can see, setting `PROMPT_COMMAND='echo hello;'` works fine and prints "hello" before every command. However, if we follow Apple's advice in an attempt to invoke `echo bye` at the end of `$PROMPT_COMMAND`, we'll get an error.

It is actually possible to do what Apple suggests but I don't want to do it because it opens up another can of worms. Namely, some people like to source `.bashrc` multiple times and I wouldn't want `gitstatus_prompt_update` to get invoked multiple times. If you want more than one thing to be invoked by `PROMPT_COMMAND`, you'll need to arrange it yourself.

**Comment by dhruvmanila** [comment]
Ah, I see. I completely understand your viewpoint and I don't have that big of an issue with this but just thought to point it out. I set the order of the variable myself starting with sourcing `gitstatus.prompt.sh`.

**Comment by romkatv** [comment]
> I set the order of the variable myself starting with sourcing `gitstatus.prompt.sh`.

Simple and effective 👍

**Comment by allir** [comment]
Hey, I want to add to this, and it's in no way a big deal, but but my issue with this is that I'm actually setting PROMPT_COMMAND in .bash_profile, for exactly this reason so that it doesn't get read every time a shell is spawned, unless it's a login shell, or .bashrc is manually sourced.

A fix for the breakage in appending to the PROMPT_COMMAND variable would be to insert a new line instead of the `;`

```
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n' }your_code_here"
```

Although that can make the output of echoing the `PROMPT_COMMAND` confusing as it will not show you the newline unless using `echo -e` .

I also completely agree with appending to the variable when using .bashrc is a bad idea, not only because some intentionally re-source it to update stuff or they just launched a new shell from inside a shell which will also re-source it so gitstatus and whatever else in there would actually run multiple times.

For me I've moved the sourcing of gitstatus.prompt.sh to my .bash_profile, which I guess makes sense in a way.

Having said all this, again, it's not a big issue, I'm using zsh most of the time anyway, which handles this better 😄 I just maintain my bash config along with it. And who knows maybe my .bash_profile + .bashrc setup is just over engineered and so it bugs me that I can't put all the things in the order that I preferred 😉
