### ISSUE TITLE
VCS_STATUS_LOCAL_BRANCH and branches without remote

### ISSUE THREAD

**Issue by nkh** [romkatv/gitstatus#266]
Hi, thanks for gitstatus

I'm trying it instead for my own status function, for speed, where I usually mark my prompt if a branch doesn't have a remote, I thought VCS_STATUS_LOCAL_BRANCH meant local without remote but it's whatever branch  that's not a head or a tag, ie it's the same branch name , with a remote or not.

I there a way to get the has_remote information?

**Comment by romkatv** [comment]
Try printing all `VCS_STATUS_*` parameters or reading the docs. I’m sure you’ll find the answer to your question.

**Comment by romkatv** [comment]
All `VCS_STATUS_*` fields are documented here: https://github.com/romkatv/gitstatus/blob/e193be52899fad2c71a6b049604b1bbdb35b0f68/gitstatus.plugin.zsh#L90-L133

There are relevant to you:

```zsh
#   VCS_STATUS_REMOTE_NAME          The remote name, e.g. "upstream" or "origin".
#   VCS_STATUS_PUSH_REMOTE_NAME     The push remote name, e.g. "upstream" or "origin".
```

The current branch has a remote if and only if `$VCS_STATUS_REMOTE_NAME` is not empty. Likewise for push remote and `$VCS_STATUS_PUSH_REMOTE_NAME`.

P.S.

My previous reply (which I've provided on a phone, hence the brevity) should've been enough for you to find the answer. Your reacting to it with a thumb down emoji is puzzling and saddening.

**Comment by nkh** [comment]
The documentation could have been in the  doc directory but instead was in the plugin for ZSH which I don't use, or it could have been in README, etc ...

Do you seriously expect arrogant answers to be liked?

But so you are not sad I will thumb up the comment that actually contained an answer

**Comment by romkatv** [comment]
> The documentation could have been in the doc directory but instead was in the plugin for ZSH which I don't use

Many things could have been better. The same docs that I linked in zsh bindings can also be found in bash bindings.

You could also print all `VCS_STATUS_*` parameters to see what you get in a repo with a remote and without one.

```bash
set | grep '^VCS_STATUS_'
```

> Do you seriously expect arrogant answers to be liked?

I expect users of free software to expend effort in trying to overcome problems by themselves (even when such problems are caused by deficiencies in the software), and, if they cannot, to ask for help. You could ask where the docs are, or how to print all `VCS_STATUS_*` parameters, for example. Your choice of using an emoji of displeasure didn't productively contribute to finding a solution to the problem.

> But so you are not sad I will thumb up the comment that actually contained an answer

No need to be rude.
