### ISSUE TITLE
./build fails on openbsd

### ISSUE THREAD

**Issue by KFDCompiled** [romkatv/gitstatus#282]
```
 ./build -h
./build[409]: formula: parameter not set
```

**Comment by romkatv** [comment]
Looks like a bug in your `/bin/sh`. Can you try it with a different interpreter?

**Comment by KFDCompiled** [comment]
that did it, worked fine with bash interpreter after I removed non-existent package install and added package g++. Here's a patchfile showing the two changes:

```
1c1
< #!/bin/sh
---
> #!/usr/local/bin/bash
94c94
<       command pkg_add install cmake gmake gcc git wget
---
>       command pkg_add cmake gmake gcc g++ git wget
```

**Comment by romkatv** [comment]
What's your default sh?

**Comment by KFDCompiled** [comment]
default OpenBSD 7.0, which I believe is ksh

**Comment by romkatv** [comment]
Can you file a bug against ksh or against OpenBSD? I really think that `build -h` should work with a POSIX sh.

**Comment by KFDCompiled** [comment]
Do you have any information that I can include to substantiate bug report? I'm looking for something more than "well, the developer said their code was POSIX compliant..."

**Comment by romkatv** [comment]
> I'm looking for something more than "well, the developer said their code was POSIX compliant..."

I don't think they'll argue.

I'm attaching a reduced file: [build.txt](https://github.com/romkatv/gitstatus/files/7639815/build.txt)

I believe the following will fail on your machine:

```shell
curl -fsSLo build.sh https://github.com/romkatv/gitstatus/files/7639815/build.txt
/bin/sh ./build.sh
```

I don't know how to reduce this file further without having access to your `/bin/sh`. However, the file is simple enough to see that it's POSIX compliant. One can search for "END" to verify that all expansions of `formula` about which `/bin/sh` complains are within a heredoc that shouldn't be expanded.

From https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html chapter 2.7.4:

> If any part of *word* is quoted, [...] the here-document lines shall not be expanded.

**Comment by KFDCompiled** [comment]
You're correct, the reduced build.txt also fails with error:
```build.sh[392]: formula: parameter not set```

I submitted a bug report to bugs@openbsd.org

**Comment by romkatv** [comment]
> I submitted a bug report to bugs@openbsd.org

I just saw it. You've attached the full script instead of the reduced one. The smaller the script, the higher the chances anyone will look at it. It's also less work for the maintainers. Ideally, you would need to reduce it to the minimum. You have access to the broken shell, so it's not much work to reduce the script even if you don't understand what it does. But even just submitting the script I've reduced would've been better than submitting the full thing.

FWIW, I was unable to reproduce this bug with `ksh` in Debian. I don't know which version it is; it does not respond to `--version` or `-V`.
