### ISSUE TITLE
gitstatus shows incorrectly untracked file

### ISSUE THREAD

**Issue by dch09** [romkatv/gitstatus#308]
Like mentioned above, gitstatus shows one untracked file. 
I've tried solutions mentioned in other, already closed issues with similar subject but I could not find the solution to my problem.

Please let me know what informations I should provide.

```
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/Desktop/project master ?1 ❯
```

**Comment by romkatv** [comment]
I'm afraid I won't have the time to fix these even if you provide all the information necessary for it. The issue is most likely caused by a mismatch in character casing in one of the files. If so, deleting the repository and cloning it anew might help.

If you manage to fix this issue, please post a comment.

**Comment by dch09** [comment]
Unfortunately re-cloning did not help. 
Could please tell me more about mentioned character mismatch in one of the files? I'd love to dig around and find a solution to post here.

**Comment by romkatv** [comment]
You might find it in the issues. I don't think this is relevant to you though because recloning didn't help.
