### ISSUE TITLE
Elvish shell support

### ISSUE THREAD

**Issue by href** [romkatv/gitstatus#33]
Just wanted to let ya'll know that there's now an integration for the [Elvish](https://elv.sh) shell over at https://github.com/href/elvish-gitstatus.

I figured I move it into my own repository as Elvish is young and pre 1.0, so there might be frequent changes not related to gitstatus. Let me know if you'd rather have the code live here.

**Comment by romkatv** [comment]
This looks cool!

It's fine by me if you keep the Elvish bindings in a separate repo but it may not be ideal for you. The output format of gitstatusd is too primitive for any kind of backward compatibility, so it changes occasionally. I make sure to update bindings in the same commit as gitstatusd so that users of said bindings don't break, but this obviously won't work if gistatusd and bindings are in different repos.

Depending on how tolerant you are of breakages we can go with the following options:

1. You _Watch_ gitstatus repo and update your code when you notice that I've committed breaking changes.
2. I @href you on breaking commits. We can combine this with (1) for redundancy.
3. You fork gitstatus, add Elvish bindings to the fork, and verify that everything works every time you pull upstream changes.
4. You send a PR to add bindings to gitstatus and then I maintain them.

I propose going with (3) for now with the long-term goal of switching to (4) when you feel that your code has become stable (that is, when Elvish itself becomes stable enough to not break user scripts on updates).

What do you think?

P.S.

What happens with gitstatusd when `elvish` dies unexpectedly? For example, when it gets killed with -9?

A related question. If Elvish exposes `exec` syscall similar to Bash/ZSH, what happens with gitstatusd on `exec elvish` or `exec bash`?

**Comment by href** [comment]
Thanks!

For now I'm okay to keep this on my side as is and I'll just watch out for changes. Once I'm confident that at least my code is stable I can create a PR (so that would be option 4, but delayed).

I'm also happy if you add me to your gitstatus commits, or if you just track them somewhere I can subscribe to (if you just mention it in the git commit I'll see it).

To your questions:

`kill -9` and `exec elvish` both work as expected (gitstatus gets killed). I assume it's because the input pipe gets closed when that happens, but I'm just guessing. I did test both of those cases and I'm glad you brought them up, because I did not before. But both leave behind no extra processes :)

**Comment by romkatv** [comment]
OK, I'll mention you on breaking gitstatusd changes. Let's keep this issue open so that it serves as a reminder for me.

Ping the issue when you think the time is ripe for a PR.

> `kill -9` and `exec elvish` both work as expected (gitstatus gets killed).

So pipe file descriptors in Elvish have `O_CLOEXEC` on them by default? This is really great. And I suppose gitstatusd dies on `SIGPIPE`. Nice.

I'd test `exec bash` for completeness, just to be sure all use cases are covered.

**Comment by romkatv** [comment]
I just noticed that your docs (and perhaps expectations) aren't accurate. I'm talking about this part:

> `result[staged]`
> The number of staged files.
> 
> `result[unstaged]`
> The number of unstaged files.
> 
> `result[untracked]`
> The number of untracked files.

Since you aren't passing any optional flags to `gitstatusd`, you get the default values of `--max-num-{staged,unstaged,untracked}`, which is `1`. This means that `result[staged]` can assume just two values: `0` if there are no staged changes, `1` if there are. Same with `result[unstaged]` and `result[untracked]`.

The defaults are set this way because it's faster, and users who only need to figure out the status of a repository shouldn't be paying the extra cost of counting changes. Presumably those who do need the counts will notice that they never get anything higher than 1 and will eventually realize they need to pass extra options.

You can pass `-1` for infinity. This is OK to do for staged and unstaged but not a good idea for untracked as it can make gitstatusd slower than the regular `git status` on a repository that has an untracked directory with a million files (`git status` won't count the files, while gitstatusd will). `--max-num-untracked=99` works well in practice if you'd like to have the number of untracked files in your prompt. The counter will saturate at 99, which is good enough to signal that you have many untracked files.

**Comment by href** [comment]
Oh, thanks for the clarifications. I'll be sure to update my docs.

I also tested `exec bash` and that works as well. So I think you are right in your assumptions, though I can't say for sure. I've just started to use Elvish and I'm not familiar with it in depth.

**Comment by zzamboni** [comment]
@romkatv - sorry to tack a somewhat unrelated question, but I am trying to port my Elvish [chain](https://github.com/zzamboni/elvish-themes/blob/master/chain.org) theme to use @href's module instead of https://github.com/muesli/elvish-libs/blob/master/git.elv (which works very well, but I want to see how much faster it gets with gitstatusd).

Something I just realized is that gitstatus does not report deleted files separately, but rather together with `unstaged`. I was wondering if you are planning to support this, since my theme has separate indicators for "unstaged" and "deleted".

Thanks!

**Comment by romkatv** [comment]
@zzamboni I don't have plans for it but it shouldn't be too difficult to implement. On the other hand, this feature is unlikely to appeal to many users. There are diminishing returns from stuffing prompt with icons. Using the same glyph for all unstaged changes -- what git calls "changes not staged for commit" in its status report -- is a good compromise.

What would you say about giving gitstatusd a try as is, and if the performance improvements turn out to be important and the loss of distinction between deleted and modified files too great, you can ping me or send a PR.

By the way, is it possible to implement an async prompt in Elvish? I see that @href's bindings are synchronous but I don't know whether it's for simplicity or because of the limitations in Elvish.

**Comment by href** [comment]
> By the way, is it possible to implement an async prompt in Elvish? I see that @href's bindings are synchronous but I don't know whether it's for simplicity or because of the limitations in Elvish.

At the moment it's surely for simplicity. It would be possible to implement an async way of querying values, but in the context of a prompt in Elvish this would be a minor optimisation imho. Elvish renders the prompt outside the main thread, so if gitstatus takes longer to finish, the prompt will be updated once that has happened.

The only thing where this might be useful is if the prompt had other computations that need time as well. Then it might make sense to have a way to query gitstatus asynchronously at the beginning of the prompt function and to get the result at the end, so some other computation could occur concurrently.

Personally I have no need for this however, since the rest of my prompt is all variables and takes next to no time to finish.

Would you agree @zzamboni? You know Elvish much better than I do.

**Comment by romkatv** [comment]
Suppose I'm in a git repo and I `cd` into another large git repo. What will happen? If the prompt will appear instantly, what will it show? It doesn't seem like it's possible for shell to automatically do the right thing.

I've recorded how it works in [Powerlevel10k](https://github.com/romkatv/powerlevel10k/) after adding `sleep(2)` to gitstatusd to simulate a huge git repository:

[![asciicast](https://asciinema.org/a/0pm9OuFzANazrHKXaBKDdJ5hz.svg)](https://asciinema.org/a/0pm9OuFzANazrHKXaBKDdJ5hz)

Prompt is always shown instantly. If this is the first time I `cd` into the specific repo, grey `loading` is shown as a placeholder for git prompt so that I know it _is_ a git repo. On subsequent visits the placeholder displays the last known state of the repo. When the true state gets known, the prompt is updated inplace (this shows as a flicker in asciinema but in a real terminal it's seamless).

To implement this logic you need to store the last state of every repo somewhere in the shell.

**Comment by zzamboni** [comment]
@romkatv @href Elvish has an asynchronous prompt mechanism, which is documented here: https://elv.sh/ref/edit.html#prompts - for this reason it is not necessary for the prompt code itself to worry about this. The prompt is always displayed instantly, and the prompt updated whenever the results become available. If the prompt function takes longer than a user-definable period of time (default 0.2 seconds), then the prompt is marked as "stale" and can be drawn in a visually distinct manner.

You can see an example here (also using a 2-second delay to emulate an extremely large git repo): https://asciinema.org/a/17pJqepWbf0ds5QgZwKvWCBhN

@romkatv WRT deleted files, I understand your reasoning - I'll give the "no separate delete indicator" a try :)

**Comment by romkatv** [comment]
That's a nice default behavior in Elvish. Certainly better than a prompt that hangs up on you. But it's not as good as what you can do in ZSH (e.g., in my screencast), isn't it? I'm asking just out of curiosity whether it's possible to define a prompt like that in Elvish.

**Comment by zzamboni** [comment]
The main difference is that your prompt shows the directory change right away and only the git part is delayed, whereas Elvish shows the old prompt entirely until the whole is updated. I think it should be possible to achieve the same effect, as both the prompt and the transformer functions can be customized. I might take a stab at it if I have some time later.

Pinging @xiaq (Elvish's author) since I think you might find this discussion interesting :)

**Comment by romkatv** [comment]
> The main difference is that your prompt shows the directory change right away and only the git part is delayed, whereas Elvish shows the old prompt entirely until the whole is updated.

Yes, everything that can be shown instantly is best shown instantly.

Another important feature of this ZSH prompt is that when stale git info is displayed, it represents the last known state of the repo rather than the last git prompt. This is important when you are `cd`-ing from one repo to another. You can see this in the screencast I posted. This is why I remarked that shell cannot do the right thing automatically for you. You have to code this logic in the prompt.

**Comment by href** [comment]
> I think it should be possible to achieve the same effect, as both the prompt and the transformer functions can be customized. I might take a stab at it if I have some time later.

Sounds like you can do that without changes to my package then? If so, that would of course be great. Otherwise let me know and I can create an issue. It should certainly be possible to implement this, if not quite as simple as the current approach.

**Comment by romkatv** [comment]
FWIW, in ZSH the logic I described (showing the last known git state, etc.) is implemented in the code that uses gitstatus bindings but not in the bindings themselves. You could do the same in Elvish. This would mean that @href's package stays as it is. However, using the package would be challenging if the best results are sought after. This is also true for ZSH -- implementing a good async prompt on top of gitstatus bindings is a lot of work. The only place where this is done to the full extent is Powerlevel10k.

**Comment by zzamboni** [comment]
I know this is difficult - before Elvish introduced async prompts, I spent **a lot** of time trying to optimize, cache and parallelize the prompt in an effort to make it work well on large repositories. Async prompts made the problem almost unnoticeable (only on very large repos), and now gitstatusd makes the staleness period pretty much unnoticeable on even my largest repositories.

What I'm trying to say is that, for me, the current state is way more than good enough, so I don't think I'll be spending any time on further optimizing the prompt :)

@romkatv thanks for your work on gitstatus, and @href thanks for introducing me to it through `elvish-gitstatus`!

**Comment by romkatv** [comment]
@zzamboni I understand you very well. The only way I can show off the fancy async behavior of my git prompt is by adding a `sleep()` into it. The largest popular git repo I know of is chromium, and gitstatusd can fetch its status in 30ms.

My questions were stemming from professional curiosity. As you can see, I've spent unreasonable amount of time building the best UX for ZSH prompt, all the way to patching libgit2 and reimplementing the core git diffing algorithm from scratch. It's way beyond the point of being useful to me personally. Naturally, I'm interested in the capabilities of a new shell. You've given me enough info to digest for a while. I've made a note for myself to try Elvish. Thank you!

**Comment by zzamboni** [comment]
@romkatv I would really encourage you to try Elvish. I have tried a lot of shells over the years, including zsh and fish, and Elvish has, in my opinion, one the nicest shell programming languages, coupled with awesome interactive features and an extremely friendly community.

**Comment by romkatv** [comment]
@href  Please update Elvish bindings to pick up the right gitstatusd binary on Android. Here's the diff from ZSH bindings that does it (just one extra line):

```zsh
diff --git a/gitstatus.plugin.zsh b/gitstatus.plugin.zsh
index 9a5f5e4..ecb47db 100644
--- a/gitstatus.plugin.zsh
+++ b/gitstatus.plugin.zsh
@@ -276,6 +276,7 @@ function gitstatus_start() {
     }
 
     local os && os=$(uname -s) && [[ -n $os ]]
+    [[ $os != Linux || $(uname -o) != Android ]] || os=Android
     local arch && arch=$(uname -m) && [[ -n $arch ]]
 
     local daemon=${GITSTATUS_DAEMON:-$dir/bin/gitstatusd-${os:l}-${arch:l}}
```

Note: `uname` has `-o` option only on Linux.

**Comment by href** [comment]
Do I get this right:

If `uname -s` returns `Linux` then I should check `uname -o` for `Android`?

**Comment by romkatv** [comment]
> If `uname -s` returns `Linux` then I should check `uname -o` for `Android`?

Correct. It's written in a roundabout way because `err_return` is in effect, so every statement must evaluate to true. Normally one could use `if` even with `err_return` but there is a bug in ZSH 5.4.2 that precludes it.

**Comment by href** [comment]
Alright, thanks for the clarification. I implemented it: https://github.com/href/elvish-gitstatus/commit/6ce737e4a161db1b8974ab6daff0a42835545c29

**Comment by romkatv** [comment]
@href Heads up that I've extended the output of gitstatusd in an incompatible way. Your code will need to be changed or it won't work with the new gitstatusd binary.

There is a new field in the output called `conflicted`. It's the number of conflicted/unmerged files. This field goes between `staged` and `untracked` in the output of gitstatusd.

**Comment by href** [comment]
Thanks, added it here: https://github.com/href/elvish-gitstatus/commit/92eae8486e479340ff5662cb50fe3b37a965ccf6

**Comment by romkatv** [comment]
Seems like this issue is no longer necessary. Closing. We know how to contact each other if we need to.

**Comment by romkatv** [comment]
@href Heads up: I've removed gitstatusd binaries from the Git repository. They can now be found in releases. The official shell bindings for Bash and Zsh automatically download appropriate binaries. Here's the basic workflow (all commands executed from `gitstatus` directory):

```zsh
% ./install -- printf '%s\n%s\n%s\n'
./usrbin/gitstatusd
v1.0.0
0
```

This call is very fast in the general case. You should issue it every time you start a new shell. It'll tell you which binary you should use, which the binary *should* have and whether `./install` has just downloaded this binary.

```zsh
% ./usrbin/gitstatusd --version-glob v1.0.0
```

Now try using the binary as usual but also pass `--version-glob` with the version obtained from `./install`. If `gitstatusd` terminates with exit code `11`, it means the binary is not the right version. In this case you need to run `./install -f` to download correct version.

```zsh
% ./install -f -- printf '%s\n%s\n%s\n'
/home/romka/.cache/gitstatus/gitstatusd-linux-x86_64
v1.0.0
1
```

This command produces output in the same format. This time the last line has `1` because the binary was just downloaded.

This should remove the need for your code to guess which binary is appropriate. For Bash and Shell bindings it also ensures that the shell code is always compatible with gitstatusd. It seems like you can only get this benefit if you fork gitstatus and put elvish bindings inside.

Happy to clarify if anything is unclear.

**Comment by href** [comment]
Thanks for the heads-up, I appreciate it! I will have a look once I find the time 😅

**Comment by href** [comment]
Since the elvish integration does not do automatic updates (you're supposed to run `gitstatus:update`), it seems to me that I can just implement this by downloading the latest version from the Releases page, whenever the update is called.

In this case I would probably not use `--version-glob` and skip all version checking during regular usage. Or is this not optional?

I can understand that you might want to streamline things across shells, but I wouldn't want to introduce a bash/zsh dependency (the install script), into a shell that does not support this. Most systems will of course support bash scripts, but that should not be a requirement for an Elvish library.

Let me know what you think. I know the Elvish integration is a the odd one here and I can understand if it bothers you that it does things differently.

**Comment by romkatv** [comment]
You can download the latest version of the appropriate gitstatusd binary with `install -f`. By default it'll download to `~/.cache/gitstatus/` but you can override this with `GITSTATUS_CACHE_DIR` environment variable.

`install` is written in POSIX shell with `/bin/sh` as interpreter. It doesn't need Bash or Zsh to run. POSIX shell exists everywhere where gitstatusd can function.

**Comment by href** [comment]
I've updated elvish-gitstatus to use the latest releases, thanks again.

Note that I kept the functioning of my plugin the same. Updates are still done by the user by manually calling `gitstatus:update`. See 7487ad93ce1e459151e6a20468ad36a8a66b17d5

**Comment by romkatv** [comment]
> I've updated elvish-gitstatus to use the latest releases, thanks again.
> 
> Note that I kept the functioning of my plugin the same. Updates are still done by the user by manually calling `gitstatus:update`. See 7487ad93ce1e459151e6a20468ad36a8a66b17d5

I'm surprised you've decided to partially reimplement `install` with some functionality loss (e.g., it won't work on MSYS2 or Cygwin, won't work in mainland China). Reimplementing it doesn't make your code more portable, more secure or more robust.

It's your code, so your call. I recommend using `install` but up to you of course. Basically, when `gitstatus:update` is called you can do this:

- Download gitstatus project to a temporary directory by any means. It's tiny compared to the binary. I'm listing options in the order of my preference. It makes almost no difference which one you use except that `git` is a bit slower and chattier.
  - `curl -fsSL https://github.com/romkatv/gitstatus/archive/master.tar.gz | tar -xz && mv gitstatus-master gitstatus`
  - `wget -qO- https://github.com/romkatv/gitstatus/archive/master.tar.gz | tar -xz && mv gitstatus-master gitstatus`
  - `git clone --depth=1 https://github.com/romkatv/gitstatus.git`
- Invoke `install` to download `gitstatusd-$kernel-$arch` to `~/.elvish/package-data`.
  - `GITSTATUS_CACHE_DIR="$HOME"/.elvish/package-data ./gitstatus/install -f`
- Rename the binary to plain `gitstatusd`.
  - `mv ~/.elvish/package-data/gitstatusd-* ~/.elvish/package-data/gitstatusd`
- Delete the temporary directory.
  - `rm -rf ./gitstatus`

There is no portability loss because `install` is at least as portable as gitstatusd itself. There is no security loss because you already put trust in gitstatusd and `install` comes from the same source and has no extra privileges.

**Comment by href** [comment]
I mainly wanted to stay close to what I already had. I might change it if anyone needs it though. I can see that there would be some advantages and I will consider it in the future.
