### ISSUE TITLE
Any benchmark update with `core.fsmonitor=true` since git 2.37.0?

### ISSUE THREAD

**Issue by linrongbin16** [romkatv/gitstatus#370]
Hi, first thanks for great work in this project.

In git 2.37.0, there is a feature file system monitor, could improve big performance. Would you please update benchmark with option `core.fsmonitor=true` and `core.untrackedcache=true`?

See: https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

**Comment by linrongbin16** [comment]
no idea, just read this blog

**Comment by romkatv** [comment]
I added an explicit note to the docs saying `core.fsmonitor` was disable in git benchmarks. I don't intend to do anything else related to `core.fsmonitor` in the near future because nothing will depend on the outcome of benchmarks if I were to re-run them with `core.fsmonitor` set to `true`. Few users have git 2.37.0+ and even fewer explicitly enable `core.fsmonitor`, which means I cannot replace `gitstatusd` powerlevel10k with plain `git`.

That said, if you are using gitstatus explicitly (not via powerlevel10k) for its performance benefits over git, consider switching to plain git if it's fast enough with `core.fsmonitor` enabled.

**Comment by bluz71** [comment]
I carried out some performance tested and documented it over at issue #385
