### ISSUE TITLE
Error when starting zsh with powerlevel10k on Linux Mint 21.1

### ISSUE THREAD

**Issue by vogonwann** [romkatv/gitstatus#381]
As title says, I'm getting error when starting zsh. Log file attached.
```
zsh --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
```
Also, after every command executed, this message is displayed in terminal:
`prompt_vcs:17: vcs_info: function definition file not found `
[gitstatus.POWERLEVEL9K.1000.3112.1681895668.1.xtrace.log](https://github.com/romkatv/gitstatus/files/11271788/gitstatus.POWERLEVEL9K.1000.3112.1681895668.1.xtrace.log)

**Comment by romkatv** [comment]
Sounds like a bug in your distribution.

**Comment by romkatv** [comment]
To clarify, the problem is caused by one of these things:

1. Zsh is missing some files.
2. Zsh isn't setting `fpath` correctly.
3. Zsh startup files set `fpath` to a wrong value.

You can narrow it down by running the following command:

```zsh
( unset FPATH && zsh -fc 'autoload -Uz +X add-zsh-hook' )
```

If this command succeeds, the issue is in (3). If it fails, the issue is either in (1) or (2).

**Comment by vogonwann** [comment]
Thanks for the quick reply. I'm getting the following:
```
( unset FPATH && zsh -fc 'autoload -Uz +X add-zsh-hook' )
zsh:1: add-zsh-hook: function definition file not found
prompt_vcs:17: vcs_info: function definition file not found    
```

**Comment by romkatv** [comment]
> Thanks for the quick reply. I'm getting the following:
> 
> ```
> ( unset FPATH && zsh -fc 'autoload -Uz +X add-zsh-hook' )
> zsh:1: add-zsh-hook: function definition file not found
> prompt_vcs:17: vcs_info: function definition file not found    
> ```

Zsh on your system is broken. Either it's missing some files or it's not setting fpath correctly. Either way it's not a problem with powerlevel10k. You'll need to figure out how to fix your zsh so that it becomes usable.

P.S.

I assume that the last line in the output is produced by your shell and NOT by the command you executed.

**Comment by vogonwann** [comment]
`exec zsh` gave output as in attached file
[exec.log](https://github.com/romkatv/gitstatus/files/11273717/exec.log)

**Comment by romkatv** [comment]
Your zsh is broken.
