### ISSUE TITLE
How to check if binary is compatible?

### ISSUE THREAD

**Issue by robobenklein** [romkatv/gitstatus#4]
Edge use case here - trying to load the plugin on a quite dated RHEL system. (School provided cluster...)

The plugin adds a whopping 5 seconds to shell startup even though it fails to load in the end - probably because it has to do some kind of library search?

![image](https://user-images.githubusercontent.com/5423266/53855564-25045600-3f9c-11e9-91d1-13e415a4b64a.png)

Is there some way I can speed up the check beforehand so it doesn't have to look through glibc versions just to end up crashed?

**Comment by robobenklein** [comment]
Actually - another idea: how about AppImage builds? They'll contain all the bundled libraries and still work as a single executable. I use them for neovim install and they've worked across almost any Linux.

**Comment by romkatv** [comment]
When loading, gitstatus plugin performs a self-check, which goes through the same code path as `gitstatus_query_dir` used by vcs prompts. Global parameters indicating that gitstatus plugin is available are set if and only if the self-check passes. This ensures vcs prompts won't attempt to use gitstatus when it doesn't work.

Since on your system gitstatus daemon fails to start, self-check fails after a 5-second timeout. I didn't try to make this faster because it's not mean to happen often. If a user installs gitstatus on a system where it doesn't work, presumably they'll disable it. There is no reason for them to source plugins that don't do anything.

Having said that, it's easy to make the self-check fail instantly in this case and I just committed a change that does that.

> Actually - another idea: how about AppImage builds?

Great idea! I didn't know about AppImage but they look promising. I'll look into it.

Another thing I can try is to link libstdc++ statically. Could you try running the version from [gitstatusdzip.zip](https://github.com/romkatv/gitstatus/files/2934777/gitstatusdzip.zip) on your ancient system? If you want to build it yourself, follow the instructions from https://github.com/romkatv/gitstatus#compiling and replace `make -j 20` at the very end with `LDFLAGS='-static-libstdc++ -static-libgcc' make -j 20`.

**Comment by robobenklein** [comment]
Your zipped version worked correctly!

**Comment by romkatv** [comment]
Closing this issue. Incompatible binaries now cause gitstatus plugin to fail to load instantly. Plus, gitstatusd now statically links C and C++ runtime, so it works more more systems.
