### ISSUE TITLE
Bundling a CLI client into the executable

### ISSUE THREAD

**Issue by mattgreen** [romkatv/gitstatus#62]
First, great work on this!

Second, I was wondering if you'd be open to PRs adding an optional CLI client into the executable. The purpose of the client is to enable a simple, text-based query interface to the information that the daemon holds. This would simplify the synchronous use case:

    > gitstatusd PROMPT --query "branch unpushed-mods"

When called like this, `gitstatusd` would:

1. Find the daemon instance with an ID of PROMPT. (I'm not sure if this is possible in the current codebase, but we could set this up via some sort of shared memory.)
2. Submit a `Request` to the daemon with the ID of PROMPT for information about the current branch, and whether any modifications are present.
3. Await a response, then print the following to standard output:
````
master
false
````
4. Exit, with status code 0 denoting success in retrieving the information, 1 denoting no git repo present, and 2 if an error occurred.

The benefit to this approach is that it is easy to read this information from any shell/language/other tool. Error information is conveyed via exit codes, as it should be. Also, only the information requested can be computed.

The only question I have is whether clients parsing the info is sufficiently fast enough for the common use case of shells. It will probably be shell dependent. I'm open to other IPC mechanisms here, but I'm not sure what would be the optimal choice beyond text output.

**Comment by romkatv** [comment]
It's a good idea to add a cli tool for querying gitstatusd. However, before doing this, I'd like to make some architectural changes.

`gitstatusd` binary should support the following commands:

- start, with an option to stay in foreground or fork; must fail fast with a documented error code if already running
- kill

The documentation should explain how to do the following:

- find out if gitstatusd is running
- send a request to gitstatusd and receive a response; must support async IO

Both of these should be possible to achieve without forking (at least on zsh). Request/response format should be simple to allow efficient and straightforward communication from shells.

gitstatusd processes should be per user (probably per `EUID` plus `EGID`), with each process serving many clients concurrently.

I'm tentatively thinking of unix domain sockets for communication and flock for synchronization. I know that it'll work well in zsh but I'll have to check how portable and how fast it'll be in bash. I might have to use tcp sockets because I recall that unix domain socket support in netcat is sketchy, plus I'm not sure how ubiquitous netcat is (although I would have to find an alternative acl mechanism as I would no longer be able to rely on filesystem permissions), and maybe drop flock. It's also possible that shells other than zsh will execute `gitstatusd` binary in "client mode" to communicate with the daemon. This means that bash bindings will fork on every request -- not ideal but might be OK.

Shell bindings should use the documented API for checking the existence of gitstatusd for the current user, starting a new daemon if necessary, and sending and receiving requests.

Finally, the cli tool you are asking for should be a separate program (preferably a shell script) that will use the same API as shell bindings. The same tool should be available as autoloadable function for zsh to avoid forking.

This has been on my TODO list for quite some time. This is sort of gitstatusd v2. It's not that much work because it requires changes only on the periphery. The hard part -- the fast git diffing algorithm -- stays unchanged. I've been postponing this work because I would also like to change the way I release binaries for gitstatusd v2, but I don't have a good solution for this yet. I'll probably need to publish debian packages, create a homebrew recipe and support fetching binaries from the latest release on GitHub.

I'm not asking you to implement this. Unless you consider yourself an expert in C++, zsh and POSIX, I probably won't be excited to receive PRs. I'm not getting paid for working on gitstatusd, so my only motivation is for working on it is fun. Reviewing PRs usually isn't (there are exceptions of course).

**Comment by romkatv** [comment]
By the way, what do you want to use gitstatusd cli for? What do you want to build on top of it?

**Comment by mattgreen** [comment]
> By the way, what do you want to use gitstatusd cli for? What do you want to build on top of it?

Original motivation was to simplify writing a binding for fish, which I was evaluating for my own shell. I'll probably stick with bash/zsh for now as it is hard to unlearn. (I could use bass to bridge the two, but it occurred to me that there was a simpler interface in the design space.)

> Unless you consider yourself an expert in C++, zsh and POSIX, I probably won't be excited to receive PRs.

I'm an expert on C++ and POSIX, but not zsh. I totally understand your motivation to want to undertake this yourself; it is a similar place that I find myself in my own projects. Cheers!

**Comment by romkatv** [comment]
> Original motivation was to simplify writing a binding for fish, which I was evaluating for my own shell. I'll probably stick with bash/zsh for now as it is hard to unlearn. (I could use bass to bridge the two, but it occurred to me that there was a simpler interface in the design space.)

Writing bindings for fish shouldn't be difficult with the current API, and this API isn't going away. If you forgo async support, multiple daemons per shell and cleanup on exec (this is definitely reasonable to get started), it should be about 100 lines of straightforward code. [Elvish bindings](https://github.com/href/elvish-gitstatus/blob/master/gitstatus.elv) are the simplest, so you could read them for inspiration. That, plus `gitstatusd --help` should be enough to get going.

On the other hand, if you have a decent zsh setup, switching to fish will likely be a net negative on your shell experience. The biggest selling point of fish is that it's usable with the default configuration (zsh isn't). If you are willing invest (or have already invested) time into configuring your shell, fish loses its appeal quickly.

**Comment by hnspn** [comment]
this could be useful inside and editor like nvim
