### ISSUE TITLE
Feature request: provide more distinct counters per type (modified unstaged, deleted unstaged, etc.)

### ISSUE THREAD

**Issue by maximbaz** [romkatv/gitstatus#64]
I can see you provide `VCS_STATUS_NUM_UNSTAGED` which shows any modification to tracked files, however I personally found it very useful to distinguish "modified" and "deleted" files.

https://github.com/maximbaz/spaceship-prompt/blob/25b1559fb6f27a44e83df8aff1be557566d9f747/sections/git_status.zsh#L62-L70

I'm not proposing you remove `VCS_STATUS_NUM_UNSTAGED`, but maybe you would consider providing two new variables `VCS_STATUS_NUM_MODIFIED` and `VCS_STATUS_NUM_DELETED`?

**Comment by romkatv** [comment]
The output of `git status` lists the difference between index and workdir in 4 sections:

- changes to be committed
- unmerged paths
- changes not staged for commit
- untracked files.

Here's an example.

```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   a

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both added:      b

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   c
	deleted:    d
	typechange: e

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	f
```

Within all but the last section each change is further annotated. For example, in the output above there are three changes not staged for commit: one modified, one deleted and one typechange. Changes to be committed and unmerged paths can also contain various annotations.

Currently gitstatusd provides counters for the number of entries in each section. It might be useful if it also provided counters for each annotation within each section. I can see value in that. I'm not very enthusiastic about doing something in between because it would require making arbitrary decisions about what should and shouldn't have a counter, and would encourage the creation of prompts that mix counters from different levels of hierarchy (like in Spaceship). In other words, having a counter for each section of `git status` output in your prompt is conceptually simpler than having counters that don't easily correspond to the output of `git status`.

May I suggest that you try using zsh without the counter for deleted files for some time and see if you prefer it?

**Comment by maximbaz** [comment]
Thanks for the response 🙂 

I know already I value my "deleted" indicator too much, so I will be missing it!

I agree with you, it makes sense not to implement anything in between if there is a way to implement a powerful API, that will cover all current and future needs (and in this particular example let users come up with their own definition of what to count as "deleted").

So if that's not too much complicated, please implement counters for annotations within each section! 🙏 

May I also suggest to implement the opposite, a counter for "is _anything_ changed in repo"? Currently I ended up with the following:

```
  vcs+='${${$(( VCS_STATUS_STASHES + VCS_STATUS_NUM_CONFLICTED + VCS_STATUS_NUM_UNSTAGED + VCS_STATUS_NUM_UNTRACKED + VCS_STATUS_NUM_STAGED + VCS_STATUS_COMMITS_BEHIND + VCS_STATUS_COMMITS_AHEAD )):#0}:+...............}'
```

By the way, otherwise my experience is quite smooth, love your work!

**Comment by romkatv** [comment]
> So if that's not too much complicated, please implement counters for annotations within each section! 🙏

Yep, I like this. It's hard though, because of renames and blob<->tree changes. I'll probably get to this eventually but not soon.

I'll try to come up with a stop-gap solution for you.

> May I also suggest to implement the opposite, a counter for "is _anything_ changed in repo"?

Everyone has a different definition of a dirty repo. Some want to include stashes and ahead/behind there, others don't. What you had to write is clear and flexible. (I'm ignoring the fact that it's an expansion, which is a bit esoteric. When I wrote this API I didn't know what it's possible to call functions during prompt expansions without forking. With the benefit of the hindsight it would've made the API much simpler. It's still possible to implement it and make new configs use it, while the old configs will still use expansions.)

**Comment by maximbaz** [comment]
> > So if that's not too much complicated, please implement counters for annotations within each section! 🙏
> 
> Yep, I like this. It's hard though, because of renames and blob<->tree changes. > I'll probably get to this eventually but not soon.
> 
> I'll try to come up with a stop-gap solution for you.

Okay, thanks! I was thinking to perhaps include the command below (as much as it pains me to use plain `git status` together with your `gitstatus`), but I'm a bit lost in the syntax for `vcs+=...`

```
if $(git status --porcelain -b | grep '^[ MARC]D ' &>/dev/null); then 
  echo 'D'
fi
```

(I don't need an actual count, in my prompt I just need to know if there are any deleted files or not).

> > May I also suggest to implement the opposite, a counter for "is anything changed in repo"?
> 
> Everyone has a different definition of a dirty repo. Some want to include stashes and ahead/behind there, others don't. 

True that, you are right.

> What you had to write is clear and flexible. (I'm ignoring the fact that it's an expansion, which is a bit esoteric. When I wrote this API I didn't know that it's possible to call functions during prompt expansions without forking. With the benefit of the hindsight it would've made the API much simpler. At some point I'd like to add a new function-based API for content customization. New configs use it, while the old configs will still use expansions.)

Yeah I struggle quite a bit with figuring out the proper syntax, but I agree this is flexible - in fact exactly what we now want for the detailed per-section counts 😉

**Comment by maximbaz** [comment]
If this helps, I've just pushed [my powerlevel10k config](https://github.com/maximbaz/dotfiles/blob/bef8e6b9ecc90059a36e79b5ff2fc896756f8a3a/.zsh/prompt.zsh#L95-L113) - I adopted the approach of showing colorful circles that tell me what kind of changes there are in the repo (e.g. blue circle means there are untracked files, red circle would mean there are removed files to commit, yellow circle means there are edited files, etc.)

![image](https://user-images.githubusercontent.com/1177900/66276172-97217e00-e890-11e9-8d07-cbffe54baef6.png)

**Comment by romkatv** [comment]
> Yeah I struggle quite a bit with figuring out the proper syntax

Maybe it'll help to look at https://github.com/romkatv/gitstatus/blob/master/gitstatus.prompt.zsh? It assembles the same string but using a regular function instead of expansions.

And I suppose you realize that you can put `$(my-function)` in the `vcs` string.

**Comment by maximbaz** [comment]
Yeah this helps thanks!

**Comment by romkatv** [comment]
> If this helps, I've just pushed [my powerlevel10k config](https://github.com/maximbaz/dotfiles/blob/bef8e6b9ecc90059a36e79b5ff2fc896756f8a3a/.zsh/prompt.zsh#L95-L113) - I adopted the approach of showing colorful circles that tell me what kind of changes there are in the repo (e.g. blue circle means there are untracked files, red circle would mean there are removed files to commit, yellow circle means there are edited files, etc.)
> 
> ![image](https://user-images.githubusercontent.com/1177900/66276172-97217e00-e890-11e9-8d07-cbffe54baef6.png)

This looks nice. There quite a few things that you can remove from the config as they have no effect. Things like parameters set to their default values, or defense against crazy environments (yours is very unlikely to need them). I can send you a PR if that's OK.

**Comment by maximbaz** [comment]
>  I can send you a PR if that's OK.

Would highly appreciate!

**Comment by romkatv** [comment]
Sent https://github.com/maximbaz/dotfiles/pull/15.

By the way, p10k supports hot-reload of parameters, meaning that you can set/unset/change any `POWERLEVEL9K` parameter interactively on the command line and it will take effect immediately. You can even add extra elements to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`. This feature is mostly useful when tuning colors or experimenting with styles. Unfortunately, it's not easy to discover and people don't expect themes to support this.

**Comment by romkatv** [comment]
I added `VCS_STATUS_NUM_UNSTAGED_DELETED` with a note that it's experimental. I'll promote it to supported if you find it useful and don't report any issues. The semantics of `VCS_STATUS_NUM_UNSTAGED` has stayed unchanged.

As far as I understand, you want to show an icon in your prompt if `(( VCS_STATUS_NUM_UNSTAGED_DELETED ))`, and another icon if `(( VCS_STATUS_NUM_UNSTAGED > VCS_STATUS_NUM_UNSTAGED_DELETED ))`. The latter means that Git repo has unstaged changes other than deletions.

I don't want to rebuild gitstatusd on all supported platforms just for this change. Please post the output of the following command so that I know which binary to rebuild:

```zsh
GITSTATUS_LOG_LEVEL=DEBUG zsh -ic 'grep -F "argv[0]" $GITSTATUS_DAEMON_LOG_POWERLEVEL9K'
```

**Comment by maximbaz** [comment]
Thank you so much! This is sufficient for my use-case, I'm testing right now, so far works well and I haven't spotted anything weird. Will let you know if I find any issue.

```
GITSTATUS_LOG_LEVEL=DEBUG zsh -ic 'grep -F "argv[0]" $GITSTATUS_DAEMON_LOG_POWERLEVEL9K'
```

This commands prints nothing for me, but no worries, it's very easy to compile the binary 😉

**Comment by maximbaz** [comment]
@romkatv just discovered the following crash:

```
() {
 emulate -L zsh
 setopt err_return no_unset
 local tmp
 tmp="$(mktemp -d ${TMPDIR:-/tmp}/repo.XXXXXXXXXX)"
 cd $tmp
 git init
 touch a
 git add a
 git commit -m 1
 rm a
 # command below will crash gitstatus process
 git add a
}
```

**Comment by romkatv** [comment]
> just discovered the following crash

Ouch! Apparently I've introduced a bug in libgit2 while fixing another one. Fixed now. Please rebuild. Make sure to pick up the newest libgit2. If you delete the previous build directory, `build.zsh` should work.

Thanks a ton for reporting this and providing a good test case.

**Comment by maximbaz** [comment]
Fix confirmed, thanks 👍 🎉

**Comment by romkatv** [comment]
Going to close this now as I don't plan to add extra counters any time soon. Will revisit once (and if) I get to work on [gitstatus v2](https://github.com/romkatv/gitstatus/issues/62#issuecomment-538651254). Proper counters need a second pass over staged and unstaged files which might be costly. To avoid paying for what you don't need, the list of counters should be specified in the request.
