### ISSUE TITLE
Using ${GITSTATUS_PROMPT} in zsh prompt creates an extra space when not in a git repository

### ISSUE THREAD

**Issue by PopeRigby** [romkatv/gitstatus#80]
When inserting `${GITSTATUS_PROMPT}` into my prompt in my `.zshrc`, it creates an extra space in the prompt when I'm not in a git repository. 

So it looks like this with `${GITSTATUS_PROMPT}`:
![Screenshot_20191122_164801](https://user-images.githubusercontent.com/20866468/69469870-1fc48280-0d48-11ea-812e-ce66034ae6ce.png)
`PROMPT='%F{blue}%~%f ${GITSTATUS_PROMPT} %(!.%F{red}%B>%b%f .%F{yellow}%B>%b%f '`

And this without:
![Screenshot_20191122_164830](https://user-images.githubusercontent.com/20866468/69469896-3d91e780-0d48-11ea-89cc-df44ce890ad4.png)
`PROMPT='%F{blue}%~%f %(!.%F{red}%B>%b%f .%F{yellow}%B>%b%f '`

**Comment by romkatv** [comment]
Consider this definition of `PROMPT`:

```zsh
PROMPT='%F{blue}%~%f ${GITSTATUS_PROMPT} %(!.%F{red}%B>%b%f .%F{yellow}%B>%b%f '
```

When `${GITSTATUS_PROMPT}` is empty, you get this:

```zsh
PROMPT='%F{blue}%~%f  %(!.%F{red}%B>%b%f .%F{yellow}%B>%b%f '
```

Note the two consecutive spaces. This is exactly what you see.

You can use `${GITSTATUS_PROMPT:+ }` to insert a space if `${GITSTATUS_PROMPT}` is not empty.

```zsh
PROMPT='%F{blue}%~%f ${GITSTATUS_PROMPT}${GITSTATUS_PROMPT:+ }%(!.%F{red}%B>%b%f .%F{yellow}%B>%b%f '
```

Consider using [powerlevel10k](https://github.com/romkatv/powerlevel10k/) instead of manually tweaking `PROMPT`.
