### ISSUE TITLE
Fresh initialised repo not recognised

### ISSUE THREAD

**Issue by dritter** [romkatv/gitstatus#9]
When I do a fresh `git init`, gitstatusd reports `norepo-sync`, which is suprising to me. Probably it is me doing something wrong..

Here is a screenshot of my approach (ignore the vcs segment here):
![Bildschirmfoto 2019-03-24 um 01 40 43](https://user-images.githubusercontent.com/1544760/54873436-7dc65200-4dd6-11e9-84f0-222a8bc80b21.png)

**Comment by romkatv** [comment]
That's me being lazy. Thanks for keeping me honest.

Empty repos are very special, for they don't have HEAD. Or rather they have only symbolic head that doesn't resolve to a commit. This means the regular APIs don't work for them. This is why I simply added `if (empty_repo) return no_repo` and figured I'll get back to it when someone complains. Well, the time has come.

I've implemented support for empty repos now. Should be consistent with `vcs_info`. There is still no support for bare repos because I'm not sure what people actually expect. `git status` doesn't pick them up. Anyway, when someone complains, I'll look into it.

I haven't pushed a new release yet because I have several optimizations in the pipeline that I'd like to finish. Don't want to create too much churn. I'll push the new binaries tomorrow. If you are in a hurry, build from source.

**Comment by romkatv** [comment]
I've pushed a new release. It contains a dozen different changes, including:

  * synchronization bug fixes in libgit2; even though libgit2 is supposedly thread-safe, I think few people use it under the stress that gitstatus puts on the library
  * optimizations in libgit2; my version is now almost 10x faster than the original libgit2
  * optimizations in gitstatus, mainly around tag scans but also in the sharding algorithm that splits repo into disjoint pieces that can be worked on in parallel
  * and bugfixes in gitstatus; apart from a few minor things (logs can be mangled) there was a serious bug in sharding which could result in false positives for "unstaged"
  * of course, empty repo support is also there

gitstatus now gives you results 2-3 times faster than a single `git status` call in every repo I tried. In chromium, the biggest repo I tested, gitstatus gives results in 105 ms on my machine. I really wanted to get it under 100 ms and occasionally I see it but on average it's still slightly above. Oh well.

Given the number of changes, including some invasive stuff in libgit2, there might be bugs. Please look out for anything weird and give me a shout if something doesn't look right.
